CREATE TABLE `DepartureMovement` (
`Id` int(11) NOT NULL AUTO_INCREMENT,
  `MovementId` INT NOT NULL,
  `AircraftId` INT NULL,
  `AircraftTypeId` INT NULL,
  `MovementDatetime` DATETIME NULL,
  `RouteId` INT NULL,
  `AirlineId` INT NULL,
  `FlightId` VARCHAR(10) NULL,
  `ScheduledDatetime` DATETIME NULL,
  `StandId` INT NULL,
  `ChuteId` INT NULL,
  `GateId` INT NULL,
  `GateStatus` VARCHAR(20) NULL,
  `PaxAdult` INT NULL,
  `PaxCount` INT NULL,
  `StatusDep` VARCHAR(20) NULL,
  `Qualifier` VARCHAR(128) NULL,
  `HandlerDep` VARCHAR(20) NULL,
  `EstimatedTime` DATETIME NULL,
  `ConfidentTime` DATETIME NULL,
  `PaxChild` INT NULL,
  `SuffixId` VARCHAR(10) NULL,
  `RemarksDep` TEXT NULL,
  `GateCloseTime` DATETIME NULL,
  `ChocksOn` DATETIME NULL,
  `ChocksOff` DATETIME NULL,
  `AllocatedCount` INT NULL,
  `PBB1Start` DATETIME NULL,
  `PBB1End` DATETIME NULL,
  `PBB2Start` DATETIME NULL,
  `PBB2End` DATETIME NULL,
  `PBB3Start` DATETIME NULL,
  `PBB3End` DATETIME NULL,
  `GateChangeLog` VARCHAR(1024) NULL,
  `PaxInfant` INT NULL,
  `NonOperational` INT NULL,
  `NonSeasonal` INT NULL,
  `StartBoarding` DATETIME NULL,
  `EndBoarding` DATETIME NULL,
  `StandAllocation` VARCHAR(10) NULL,
  `CallSignId` VARCHAR(20) NULL,
  `ConfidentPaxCount` INT NULL,
  `BaggageLoadTotal` INT NULL,
  `ChuteChangeLog` VARCHAR(128) NULL,
  `MeastroDCS` TINYINT(1) NULL,
  `CounterDetail` VARCHAR(128) NULL,
  `Status` INT NULL DEFAULT 0,
  `GateCloseTime1` DATETIME NULL,
  `GateCloseTime2` DATETIME NULL,
  `StartBoarding1` DATETIME NULL,
  `StartBoarding2` DATETIME NULL,
  `EndBoarding1` DATETIME NULL,
  `EndBoarding2` DATETIME NULL,
  `StartRecheckin1` DATETIME NULL,
  `StartRecheckin2` DATETIME NULL,
  `RecheckinChangeLog` VARCHAR(256) NULL,
  
  `BatchDate` DATETIME NULL,
  `MovementSourceDataVersion` INT NULL,
  `Status_B` CHAR(10) NULL,
  `ResponseCode` VARCHAR(50) NULL,
  `ModifiMovementId` VARCHAR(164) NULL,
  `Status_A` TINYINT NOT NULL DEFAULT 0,
  `FrontCounter` INT NULL DEFAULT 0,
  `TransferCounter` INT NULL DEFAULT 0,
  `GateReBoarding` VARCHAR(30) NULL DEFAULT '0',
  `CreatedDate` DATETIME NULL, 
  `ResponsedDate` DATETIME NULL,
  
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
